builders:

  translationBuilder:
    target: ":translation"
    import: "package:translation/builders.dart"
    builder_factories: [ "translationBuilder" ]
    build_extensions: { ".dart": [ "translation.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ['fair_compiler']